language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - pip install -r _utilities/requirements.txt
  - pip install coveralls
  - pip install coverage
# command to run tests
script: 
  - coverage run _utilities/test.py

after_success:
  - coveralls